version: 1

disable_existing_loggers: False

loggers:
    root:
        level: DEBUG
        handlers:
            - queue_handler
    test:
        level: DEBUG
        handlers:
            - stdout
            - stderr
            - stdfile

filters:
    non_error:
        (): ulogger.NonErrorFilter

formatters:
    stdfmtter:
        format: "[%(asctime)s][%(levelname)s][%(module)s:L%(lineno)d] : %(message)s"
        datefmt: "%Y-%m-%dT%H:%M:%S%z"
    jsonfmtter:
        (): ulogger.JSONFormatter
        fmt_keys:
            level: levelname
            message: message
            timestamp: timestamp
            logger: name
            module: module
            function: funcName
            line: lineno
            thread_name: threadName

handlers:
    stdout:
        class: logging.StreamHandler
        filters:
            - non_error
        formatter: stdfmtter
        stream: ext://sys.stdout
    stderr:
        class: logging.StreamHandler
        level: WARNING
        formatter: stdfmtter
        stream: ext://sys.stderr
    stdfile:
        class: concurrent_log_handler.ConcurrentRotatingFileHandler 
        filename: ./logs/logs.jsonl
        mode: a
        level: DEBUG
        formatter: jsonfmtter
        maxBytes: 2097152
        encoding: utf8
    queue_handler:  # Send logs to a queue without blocking the main thread
        class: logging.handlers.QueueHandler
        handlers:
            - stdout
            - stderr
            - stdfile
        respect_handler_level: True